#!/usr/bin/env bash
# ============================================================================
# tests/run.sh — Node test runner for the Sky Intruders PJSR libraries
# ============================================================================
#
# PixInsight scripts cannot run headless, so the strategy is:
#   1. strip any PixInsight preprocessor lines (#feature-id, #include,
#      #define with line continuations) from the lib files;
#   2. build tests/build/module.js: the stripped libs concatenated + a
#      module.exports block exposing the pure-logic namespaces
#      (SIStats, SIFrameMetaCore, SITrailCore);
#   3. syntax-check that exact file with node --check, then run every
#      tests/*.test.js against it.
#
# The PixInsight-facing wrappers (SIFrameMeta.read, SITrailDetect.detect)
# are exercised manually in PixInsight — two-gate validation per
# PJSR-NOTES section 8.
#
# Usage: bash tests/run.sh
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/tests/build"
MODULE="$BUILD/module.js"
LIBS=(
   "$ROOT/pjsr/lib/Stats.js"
   "$ROOT/pjsr/lib/FrameMeta.js"
   "$ROOT/pjsr/lib/TrailDetect.js"
)

mkdir -p "$BUILD"

{
   echo '// Generated by tests/run.sh — do not edit'

   # Strip PI preprocessor directives (including multi-line continuations)
   # and CR line endings; the lib files are plain JS otherwise.
   for lib in "${LIBS[@]}"; do
      echo "// ---- $(basename "$lib") ----"
      awk '{ sub(/\r$/,"") } cont { cont = /\\$/; next } /^#/ { cont = /\\$/; next } { print }' "$lib"
   done

   # Expose the pure-logic namespaces under test
   cat <<'EOF'

module.exports = {
   SIStats: SIStats,
   SIFrameMetaCore: SIFrameMetaCore,
   SITrailCore: SITrailCore
};
EOF
} > "$MODULE"

# Check the exact file the tests load (lib bodies AND exports block)
node --check "$MODULE"
echo "OK   syntax (node --check)"

failures=0
for t in "$ROOT"/tests/*.test.js; do
   if node "$t" > "$BUILD/last.log" 2>&1; then
      echo "OK   $(basename "$t")"
   else
      echo "FAIL $(basename "$t")"
      cat "$BUILD/last.log"
      failures=1
   fi
done

if [ "$failures" -ne 0 ]; then
   echo "Tests failed." >&2
   exit 1
fi
echo "All tests passed."
