/*
 * Report.js — the night log: chronology, fun stats, personal records and a
 * Reddit-ready markdown post.
 *
 * Everything except loadHistory/saveHistory is pure JS (Node-testable).
 * History is a full-rewrite JSON file (PJSR append is broken under v8).
 */

var SIReport = ( function()
{
   var STRINGS = {
      en: {
         title: "Sky Intruders — night log",
         session: "Session",
         framesAnalyzed: "%1 frames analyzed, %2 total exposure",
         nothing: "Nobody crossed your photo tonight. A perfectly boring, perfectly clean night — frame it.",
         chronology: "Who crossed the field",
         satellites: "satellites",
         meteors: "meteor candidates",
         satCandidates: "uncataloged satellite candidates",
         unknowns: "unidentified trails",
         planes: "airplane(s)",
         trains: "satellite train(s) — fresh launches, not yet cataloged",
         predicted: "Predicted crossers (no matched trail)",
         movers: "asteroid candidates (slow movers)",
         funStats: "Night stats",
         operators: "Operator breakdown",
         cleanFrames: "%1 of %2 frames came out untouched (%3%)",
         busiestHour: "Rush hour: %1 (%2 crossings)",
         records: "Personal records",
         newRecord: "NEW RECORD",
         recSats: "most satellites in one night: %1 (previous best %2)",
         recStarlink: "most Starlink in one night: %1 (previous best %2)",
         recMeteors: "most meteor candidates in one night: %1 (previous best %2)",
         firstNight: "First logged night — every stat is a personal record. Welcome to the club.",
         redditTitle: "Sky Intruders report: %1 satellites%2 crossed my %3 session last night",
         redditMeteors: " and %1 meteor(s)",
         moverLine: "%1 arcsec/min over %2 frames, from %3",
         confidence: { low: "low confidence", medium: "probable", high: "confirmed" },
         generatedBy: "Report generated by Sky Intruders for PixInsight — pixinsight-scripts.caelo.works"
      },
      fr: {
         title: "Sky Intruders — journal de nuit",
         session: "Session",
         framesAnalyzed: "%1 brutes analysées, %2 de pose cumulée",
         nothing: "Personne n'a traversé ta photo cette nuit. Une nuit parfaitement banale, parfaitement propre — à encadrer.",
         chronology: "Qui a traversé le champ",
         satellites: "satellites",
         meteors: "candidats météores",
         satCandidates: "candidats satellites hors catalogue",
         unknowns: "traînées non identifiées",
         planes: "avion(s)",
         trains: "train(s) de satellites — lancements récents, pas encore catalogués",
         predicted: "Passages prédits (sans traînée appariée)",
         movers: "candidats astéroïdes (objets lents)",
         funStats: "Stats de la nuit",
         operators: "Répartition par opérateur",
         cleanFrames: "%1 brutes sur %2 sont sorties indemnes (%3 %)",
         busiestHour: "Heure de pointe : %1 (%2 passages)",
         records: "Records personnels",
         newRecord: "NOUVEAU RECORD",
         recSats: "record de satellites en une nuit : %1 (ancien record %2)",
         recStarlink: "record de Starlink en une nuit : %1 (ancien record %2)",
         recMeteors: "record de candidats météores en une nuit : %1 (ancien record %2)",
         firstNight: "Première nuit enregistrée — chaque stat est un record personnel. Bienvenue au club.",
         redditTitle: "Rapport Sky Intruders : %1 satellites%2 ont traversé ma session %3 cette nuit",
         redditMeteors: " et %1 météore(s)",
         moverLine: "%1 arcsec/min sur %2 brutes, depuis %3",
         confidence: { low: "confiance faible", medium: "probable", high: "confirmé" },
         generatedBy: "Rapport généré par Sky Intruders pour PixInsight — pixinsight-scripts.caelo.works"
      }
   };

   function fmt( template )
   {
      var s = template;
      for ( var i = 1; i < arguments.length; ++i )
         s = s.replace( "%" + i, String( arguments[ i ] ) );
      return s;
   }

   function pad2( n )
   {
      return ( n < 10 ? "0" : "" ) + n;
   }

   function localTime( date )
   {
      return pad2( date.getHours() ) + ":" + pad2( date.getMinutes() );
   }

   function exposureLabel( totalSec )
   {
      var h = Math.floor( totalSec / 3600 );
      var m = Math.round( ( totalSec - h * 3600 ) / 60 );
      return ( h > 0 ) ? h + "h" + pad2( m ) : m + " min";
   }

   // Operator from the catalog name — coarse on purpose, it feeds fun stats.
   function classifyOperator( name )
   {
      var n = ( name || "" ).toUpperCase();
      if ( n.indexOf( "STARLINK" ) >= 0 ) return "Starlink";
      if ( n.indexOf( "ONEWEB" ) >= 0 ) return "OneWeb";
      if ( n.indexOf( "ISS" ) >= 0 || n.indexOf( "ZARYA" ) >= 0 ) return "ISS";
      if ( n.indexOf( "CSS" ) >= 0 || n.indexOf( "TIANGONG" ) >= 0 ) return "Tiangong";
      if ( n.indexOf( "IRIDIUM" ) >= 0 ) return "Iridium";
      if ( n.indexOf( "GLOBALSTAR" ) >= 0 ) return "Globalstar";
      if ( n.indexOf( "FLOCK" ) >= 0 || n.indexOf( "SKYSAT" ) >= 0 ) return "Planet";
      if ( n.indexOf( "LEMUR" ) >= 0 ) return "Spire";
      if ( n.indexOf( "KUIPER" ) >= 0 ) return "Kuiper";
      if ( n.indexOf( "QIANFAN" ) >= 0 || n.indexOf( "G60" ) >= 0 ) return "Qianfan";
      if ( n.indexOf( " DEB" ) >= 0 ) return "debris";
      if ( n.indexOf( "R/B" ) >= 0 ) return "rocket body";
      return "other";
   }

   /*
    * events: [ { timeUtc (Date), klass ("satellite"|"meteor"|
    *   "satellite-candidate"|"unknown"), name, shower, confidence, frameId,
    *   elevationDeg, angularRateDegPerSec, details } ]
    * night: { dateLabel, frames: N, cleanFrames, totalExposureSec,
    *          target (string|null), events, movers }
    */
   function summarizeNight( night )
   {
      var sats = 0, starlink = 0, meteors = 0, satCand = 0, planes = 0, trains = 0, unknowns = 0;
      var operators = {};
      var notable = [];
      for ( var i = 0; i < night.events.length; ++i )
      {
         var e = night.events[ i ];
         if ( e.klass == "satellite" )
         {
            sats++;
            var op = classifyOperator( e.name );
            operators[ op ] = ( operators[ op ] || 0 ) + 1;
            if ( op == "Starlink" )
               starlink++;
            else if ( notable.length < 5 )
               notable.push( e.name );
         }
         else if ( e.klass == "meteor" ) meteors++;
         else if ( e.klass == "satellite-candidate" ) satCand++;
         else if ( e.klass == "plane" ) planes++;
         else if ( e.klass == "train" ) trains++;
         else if ( e.klass == "asteroid" ) ; // counted via night.movers
         else unknowns++;
      }
      return { date: night.dateLabel, frames: night.frames,
               satellites: sats, starlink: starlink, meteors: meteors,
               satCandidates: satCand, planes: planes, trains: trains, unknowns: unknowns,
               movers: ( night.movers || [] ).length,
               operators: operators, notable: notable };
   }

   function computeRecords( summary, history, lang )
   {
      var T = STRINGS[ lang ] || STRINGS.en;
      var nights = ( history && history.nights ) ? history.nights : [];
      if ( nights.length == 0 )
         return [ T.firstNight ];
      function best( key )
      {
         var b = 0;
         for ( var i = 0; i < nights.length; ++i )
            if ( ( nights[ i ][ key ] || 0 ) > b )
               b = nights[ i ][ key ];
         return b;
      }
      var out = [];
      if ( summary.satellites > best( "satellites" ) )
         out.push( T.newRecord + " — " + fmt( T.recSats, summary.satellites, best( "satellites" ) ) );
      if ( summary.starlink > best( "starlink" ) )
         out.push( T.newRecord + " — " + fmt( T.recStarlink, summary.starlink, best( "starlink" ) ) );
      if ( summary.meteors > best( "meteors" ) )
         out.push( T.newRecord + " — " + fmt( T.recMeteors, summary.meteors, best( "meteors" ) ) );
      return out;
   }

   function eventLine( e, lang )
   {
      var T = STRINGS[ lang ] || STRINGS.en;
      var t = e.timeUtc ? localTime( e.timeUtc ) : "--:--";
      var what;
      if ( e.klass == "satellite" )
      {
         what = e.name;
         var extra = [];
         if ( e.elevationDeg != null )
            extra.push( Math.round( e.elevationDeg ) + "°" );
         if ( e.angularRateDegPerSec != null )
            extra.push( e.angularRateDegPerSec.toFixed( 2 ) + "°/s" );
         if ( extra.length )
            what += " (" + extra.join( ", " ) + ")";
      }
      else if ( e.klass == "meteor" )
         what = ( e.shower ? ( lang == "fr" ? "météore probable : " : "probable meteor: " ) + e.shower
                           : ( lang == "fr" ? "candidat météore" : "meteor candidate" ) ) +
                " [" + ( T.confidence[ e.confidence ] || e.confidence ) + "]";
      else if ( e.klass == "satellite-candidate" )
         what = ( lang == "fr" ? "satellite hors catalogue ?" : "uncataloged satellite?" ) +
                " [" + ( T.confidence[ e.confidence ] || e.confidence ) + "]";
      else if ( e.klass == "plane" )
         what = ( lang == "fr" ? "avion" : "airplane" ) +
                ( e.segments != null ? " (" + e.segments + ( lang == "fr" ? " traits" : " marks" ) + ")" : "" );
      else if ( e.klass == "train" )
         what = ( lang == "fr" ? "train de satellites" : "satellite train" ) +
                ( e.segments != null ? " (" + e.segments + ( lang == "fr" ? " traînées parallèles" : " parallel streaks" ) + ")" : "" );
      else if ( e.klass == "asteroid" )
         what = ( lang == "fr" ? "candidat astéroïde" : "asteroid candidate" ) +
                ( e.rateArcsecPerMin != null ? " (" + e.rateArcsecPerMin.toFixed( 1 ) + " arcsec/min)" : "" );
      else
         what = ( lang == "fr" ? "traînée non identifiée" : "unidentified trail" );
      return t + " — " + what + "  ·  " + e.frameId;
   }

   function busiestHour( events )
   {
      var byHour = {};
      for ( var i = 0; i < events.length; ++i )
         if ( events[ i ].timeUtc )
         {
            var h = events[ i ].timeUtc.getHours();
            byHour[ h ] = ( byHour[ h ] || 0 ) + 1;
         }
      var bestH = null, bestN = 0;
      for ( var k in byHour )
         if ( byHour[ k ] > bestN )
         {
            bestN = byHour[ k ];
            bestH = k;
         }
      return ( bestH == null ) ? null : { label: pad2( Number( bestH ) ) + ":00–" + pad2( ( Number( bestH ) + 1 ) % 24 ) + ":00", count: bestN };
   }

   function build( night, history, lang )
   {
      var T = STRINGS[ lang ] || STRINGS.en;
      var summary = summarizeNight( night );
      var records = computeRecords( summary, history, lang );
      var L = [];

      L.push( "# " + T.title + " — " + night.dateLabel );
      L.push( "" );
      var sess = fmt( T.framesAnalyzed, night.frames, exposureLabel( night.totalExposureSec ) );
      if ( night.target )
         sess = night.target + " · " + sess;
      L.push( "**" + T.session + "** : " + sess );
      L.push( "" );

      var sorted = night.events.slice().sort( function( a, b )
         { return ( a.timeUtc || 0 ) - ( b.timeUtc || 0 ); } );

      if ( sorted.length == 0 && summary.movers == 0 )
         L.push( "*" + T.nothing + "*" );
      else
      {
         L.push( "## " + T.chronology );
         L.push( "" );
         for ( var i = 0; i < sorted.length; ++i )
            L.push( "- " + eventLine( sorted[ i ], lang ) );
         L.push( "" );

         // Sunlit satellites the orbit propagation puts in the field during
         // the exposures, but that no detected trail could be matched to —
         // the honest answer to "why is nothing identified?".
         var predicted = night.predicted || [];
         if ( predicted.length > 0 )
         {
            L.push( "## " + T.predicted );
            L.push( "" );
            for ( var i = 0; i < predicted.length; ++i )
            {
               var p = predicted[ i ];
               var t = p.timeUtc ? localTime( p.timeUtc ) : "--:--";
               L.push( "- " + t + " — " + ( p.name || ( "NORAD " + p.noradId ) ) +
                       ( p.elevationDeg != null ? " (" + Math.round( p.elevationDeg ) + "°)" : "" ) +
                       "  ·  " + p.frameId );
            }
            L.push( "" );
         }

         L.push( "## " + T.funStats );
         L.push( "" );
         L.push( "- " + summary.satellites + " " + T.satellites +
                 ( summary.starlink > 0 ? " (" + summary.starlink + " Starlink)" : "" ) );
         if ( summary.meteors > 0 )
            L.push( "- " + summary.meteors + " " + T.meteors );
         if ( summary.satCandidates > 0 )
            L.push( "- " + summary.satCandidates + " " + T.satCandidates );
         if ( summary.planes > 0 )
            L.push( "- " + summary.planes + " " + T.planes );
         if ( summary.trains > 0 )
            L.push( "- " + summary.trains + " " + T.trains );
         if ( summary.unknowns > 0 )
            L.push( "- " + summary.unknowns + " " + T.unknowns );
         var pct = ( night.frames > 0 ) ? Math.round( 100 * night.cleanFrames / night.frames ) : 100;
         L.push( "- " + fmt( T.cleanFrames, night.cleanFrames, night.frames, pct ) );
         var rush = busiestHour( sorted );
         if ( rush != null && rush.count >= 2 )
            L.push( "- " + fmt( T.busiestHour, rush.label, rush.count ) );

         var opKeys = [];
         for ( var op in summary.operators )
            opKeys.push( op );
         if ( opKeys.length > 1 || summary.starlink > 0 )
         {
            L.push( "" );
            L.push( "### " + T.operators );
            L.push( "" );
            opKeys.sort( function( a, b ) { return summary.operators[ b ] - summary.operators[ a ]; } );
            for ( var j = 0; j < opKeys.length; ++j )
               L.push( "- " + opKeys[ j ] + " : " + summary.operators[ opKeys[ j ] ] );
         }

         if ( ( night.movers || [] ).length > 0 )
         {
            L.push( "" );
            L.push( "## " + T.movers );
            L.push( "" );
            for ( var m = 0; m < night.movers.length; ++m )
            {
               var mv = night.movers[ m ];
               L.push( "- " + fmt( T.moverLine, mv.rateArcsecPerMin.toFixed( 1 ),
                                   mv.points.length, mv.points[ 0 ].frame ) );
            }
         }
      }

      if ( records.length > 0 )
      {
         L.push( "" );
         L.push( "## " + T.records );
         L.push( "" );
         for ( var r = 0; r < records.length; ++r )
            L.push( "- 🏆 " + records[ r ] );
      }

      L.push( "" );
      L.push( "---" );
      L.push( "*" + T.generatedBy + "*" );

      var markdown = L.join( "\n" );
      var redditTitle = fmt( T.redditTitle, summary.satellites,
                             summary.meteors > 0 ? fmt( T.redditMeteors, summary.meteors ) : "",
                             night.target || ( lang == "fr" ? "d'astrophoto" : "astrophotography" ) );
      return { markdown: markdown, redditTitle: redditTitle, summary: summary, records: records };
   }

   // --- persistent history (PI runtime only) --------------------------------

   function historyPath()
   {
      return File.homeDirectory + "/.caeloworks/sky-intruders/history.json";
   }

   function loadHistory()
   {
      try
      {
         var p = historyPath();
         if ( File.exists( p ) )
            return JSON.parse( File.readTextFile( p ) );
      }
      catch ( e ) {}
      return { nights: [] };
   }

   function saveHistory( history )
   {
      var p = historyPath();
      var dir = File.extractDrive( p ) + File.extractDirectory( p );
      if ( !File.directoryExists( dir ) )
         File.createDirectory( dir, true );
      File.writeTextFile( p, JSON.stringify( history, null, 2 ) );
   }

   function appendNight( history, summary )
   {
      // One entry per night label: re-running the analysis replaces it.
      history.nights = history.nights.filter( function( n )
         { return n.date != summary.date; } );
      history.nights.push( summary );
      return history;
   }

   return {
      STRINGS: STRINGS,
      classifyOperator: classifyOperator,
      summarizeNight: summarizeNight,
      computeRecords: computeRecords,
      busiestHour: busiestHour,
      build: build,
      historyPath: historyPath,
      loadHistory: loadHistory,
      saveHistory: saveHistory,
      appendNight: appendNight
   };
} )();
