/*
 * TreasureReport.js — SITreasureReport: standalone illustrated HTML for the
 * Treasure Hunt. Pure string assembly (Node-testable). Everything is inlined
 * so the file is a single shareable, CSP-safe artifact: CSS in a <style>
 * block, the annotated map and per-object thumbnails embedded as
 * data:image/png;base64 URIs.
 */

var SITreasureReport = ( function()
{
   var STRINGS = {
      en: {
         title: "Sky Intruders — Treasure Hunt",
         subtitle: "What you photographed without knowing",
         field: "Field",
         center: "center",
         radius: "search radius",
         captured: "Captured treasures",
         summary: "Summary",
         forumBlock: "Forum-ready summary (copy &amp; paste)",
         galaxies: "galaxies", quasars: "quasars",
         pne: "planetary nebulae", asteroids: "asteroids",
         none: "Nothing from the deep catalogs landed in this frame.",
         generatedBy: "Generated by Sky Intruders for PixInsight — pixinsight-scripts.caelo.works"
      },
      fr: {
         title: "Sky Intruders — Chasse au tresor",
         subtitle: "Ce que vous avez photographie sans le savoir",
         field: "Champ",
         center: "centre",
         radius: "rayon de recherche",
         captured: "Tresors captures",
         summary: "Resume",
         forumBlock: "Resume pret pour le forum (copier-coller)",
         galaxies: "galaxies", quasars: "quasars",
         pne: "nebuleuses planetaires", asteroids: "asteroides",
         none: "Rien des catalogues profonds n'est tombe dans ce champ.",
         generatedBy: "Genere par Sky Intruders pour PixInsight — pixinsight-scripts.caelo.works"
      }
   };

   function esc( s )
   {
      return String( ( s === null || s === undefined ) ? "" : s )
         .replace( /&/g, "&amp;" ).replace( /</g, "&lt;" )
         .replace( />/g, "&gt;" ).replace( /"/g, "&quot;" );
   }

   function fixed( x, d )
   {
      return ( typeof x === "number" && isFinite( x ) ) ? x.toFixed( d ) : "?";
   }

   var CSS =
      "body{margin:0;background:#0c1018;color:#e6ebf2;" +
      "font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;line-height:1.5}" +
      ".wrap{max-width:none;margin:0;padding:24px clamp(16px,4vw,56px)}" +
      "h1{font-size:26px;margin:0 0 4px}h2{font-size:19px;margin:28px 0 10px;border-bottom:1px solid #263042;padding-bottom:6px}" +
      ".sub{color:#9fb0c6;margin:0 0 16px}" +
      ".field{color:#9fb0c6;font-size:14px;margin:0 0 12px}" +
      ".map{width:100%;max-width:100%;height:auto;border:1px solid #263042;border-radius:8px;display:block}" +
      ".counts{display:flex;flex-wrap:wrap;gap:10px;margin:8px 0 4px;padding:0;list-style:none}" +
      ".counts li{background:#151c28;border:1px solid #263042;border-radius:20px;padding:6px 14px;font-size:14px}" +
      ".counts b{font-size:18px;color:#7fd1ff}" +
      ".head{margin:6px 0 0;padding-left:18px}.head li{margin:2px 0}" +
      ".treasures{list-style:none;padding:0;margin:0}" +
      ".t{display:flex;gap:14px;align-items:flex-start;padding:12px 0;border-bottom:1px solid #1b2331}" +
      ".t img{width:96px;height:96px;object-fit:cover;border-radius:6px;border:1px solid #263042;flex:0 0 auto;background:#000}" +
      ".t .body{flex:1 1 auto;min-width:0}" +
      ".t .name{font-weight:600}" +
      ".badge{display:inline-block;font-size:11px;text-transform:uppercase;letter-spacing:.04em;" +
      "padding:2px 8px;border-radius:10px;margin-right:8px;vertical-align:middle}" +
      ".b-galaxy{background:#25324a;color:#9fc3ff}.b-quasar{background:#3a2540;color:#e39bff}" +
      ".b-pne{background:#24403a;color:#8ff0cf}.b-asteroid{background:#403524;color:#ffd38f}" +
      ".narr{color:#c9d4e2;margin:4px 0 0}" +
      "pre.forum{white-space:pre-wrap;background:#0f141d;border:1px solid #263042;border-radius:8px;" +
      "padding:14px;font-size:13px;color:#c9d4e2;overflow-x:auto}" +
      "footer{color:#6f7f96;font-size:12px;margin-top:28px;border-top:1px solid #263042;padding-top:12px}";

   function badge( type )
   {
      var cls = { galaxy: "b-galaxy", quasar: "b-quasar", pne: "b-pne", asteroid: "b-asteroid" }[ type ] || "b-galaxy";
      return "<span class=\"badge " + cls + "\">" + esc( type ) + "</span>";
   }

   function forumText( summary, T )
   {
      // Plain-text block a user can paste into a forum post.
      var lines = [];
      lines.push( T.title + " — " + T.subtitle );
      if ( summary && summary.headlines )
         for ( var i = 0; i < summary.headlines.length; ++i )
            lines.push( "- " + summary.headlines[ i ] );
      lines.push( "" );
      lines.push( T.generatedBy );
      return lines.join( "\n" );
   }

   function buildHtml( opts )
   {
      opts = opts || {};
      var lang = ( opts.lang === "fr" ) ? "fr" : "en";
      var T = STRINGS[ lang ];
      var treasures = opts.treasures || [];
      var narratives = opts.narratives || [];
      var summary = opts.summary || null;
      var field = opts.fieldInfo || {};

      // Index thumbnails by id for matching against treasures.
      var thumbById = {};
      var thumbs = opts.thumbs || [];
      for ( var i = 0; i < thumbs.length; ++i )
         if ( thumbs[ i ] && thumbs[ i ].id !== undefined )
            thumbById[ String( thumbs[ i ].id ) ] = thumbs[ i ].pngBase64;

      var H = [];
      H.push( "<!doctype html>" );
      H.push( "<html lang=\"" + lang + "\"><head><meta charset=\"utf-8\">" );
      H.push( "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">" );
      H.push( "<title>" + esc( T.title ) + "</title>" );
      H.push( "<style>" + CSS + "</style></head><body><div class=\"wrap\">" );

      H.push( "<h1>" + esc( T.title ) + "</h1>" );
      H.push( "<p class=\"sub\">" + esc( T.subtitle ) + "</p>" );

      // Field descriptor
      var fieldLine = T.field + " — " + T.center + " RA " + fixed( field.raDeg, 4 ) +
                      " Dec " + fixed( field.decDeg, 4 ) + ", " + T.radius + " " +
                      fixed( field.radiusDeg, 3 ) + " deg";
      if ( field.target )
         fieldLine = esc( field.target ) + " · " + fieldLine;
      H.push( "<p class=\"field\">" + fieldLine + "</p>" );

      // Annotated map
      if ( opts.mapPng )
         H.push( "<img class=\"map\" alt=\"annotated field map\" src=\"data:image/png;base64," +
                 opts.mapPng + "\">" );

      // Summary
      H.push( "<h2>" + esc( T.summary ) + "</h2>" );
      if ( summary && summary.counts )
      {
         H.push( "<ul class=\"counts\">" );
         H.push( "<li><b>" + ( summary.counts.galaxy || 0 ) + "</b> " + esc( T.galaxies ) + "</li>" );
         H.push( "<li><b>" + ( summary.counts.quasar || 0 ) + "</b> " + esc( T.quasars ) + "</li>" );
         H.push( "<li><b>" + ( summary.counts.pne || 0 ) + "</b> " + esc( T.pne ) + "</li>" );
         H.push( "<li><b>" + ( summary.counts.asteroid || 0 ) + "</b> " + esc( T.asteroids ) + "</li>" );
         H.push( "</ul>" );
         if ( summary.headlines && summary.headlines.length )
         {
            H.push( "<ul class=\"head\">" );
            for ( var s = 0; s < summary.headlines.length; ++s )
               H.push( "<li>" + esc( summary.headlines[ s ] ) + "</li>" );
            H.push( "</ul>" );
         }
      }

      // Treasures
      H.push( "<h2>" + esc( T.captured ) + "</h2>" );
      if ( treasures.length === 0 )
         H.push( "<p>" + esc( T.none ) + "</p>" );
      else
      {
         H.push( "<ul class=\"treasures\">" );
         for ( var t = 0; t < treasures.length; ++t )
         {
            var o = treasures[ t ];
            var id = ( o.id !== undefined ) ? String( o.id ) : String( t );
            var png = thumbById[ id ];
            if ( png === undefined && o.pngBase64 )
               png = o.pngBase64;
            H.push( "<li class=\"t\">" );
            if ( png )
               H.push( "<img alt=\"" + esc( o.name ) + "\" src=\"data:image/png;base64," + png + "\">" );
            H.push( "<div class=\"body\">" );
            H.push( "<div class=\"name\">" + badge( o.type ) + esc( o.name ) + "</div>" );
            var narr = ( t < narratives.length ) ? narratives[ t ] : "";
            if ( narr )
               H.push( "<p class=\"narr\">" + esc( narr ) + "</p>" );
            H.push( "</div></li>" );
         }
         H.push( "</ul>" );
      }

      // Forum block
      if ( summary )
      {
         H.push( "<h2>" + T.forumBlock + "</h2>" );
         H.push( "<pre class=\"forum\">" + esc( forumText( summary, T ) ) + "</pre>" );
      }

      H.push( "<footer>" + esc( T.generatedBy ) + "</footer>" );
      H.push( "</div></body></html>" );
      return H.join( "\n" );
   }

   return {
      STRINGS: STRINGS,
      esc: esc,
      buildHtml: buildHtml
   };
} )();
